### ISSUE TITLE
rubygems out of date?

### ISSUE THREAD

**Issue by mooreniemi** [hayeah/rantly#33]
When I did gem install rantly, the version I received didn't have any of the extensions for me to require in. I had to use gem "rantly", :git => 'https://github.com/hayeah/rantly' to get it to work.

**Comment by abargnesi** [comment]
+1

**Comment by twopoint718** [comment]
+1

**Comment by abargnesi** [comment]
Reopened at https://github.com/abargnesi/rantly/issues/1.
