### ISSUE TITLE
Create top-level rantly organization?

### ISSUE THREAD

**Issue by nightscape** [hayeah/rantly#36]
Hi @hayeah,

it seems that rantly development is progressing rather slowly.
What do you think of creating a top-level rantly organization and inviting more people as admins to the repository?
Rantly is one of the few options if you want to do property-based testing and it could use some community love ;)

Best
  Martin

**Comment by niftyn8** [comment]
@nightscape if hayeah doesn't respond for a very long time I've been looking at moving forward with https://github.com/justincampbell/generative. Justin gave me admin access pretty quick and he and I both respond fairly quick to PRs. Wouldn't be a big deal to create a organization for it.

Generative though is more of a hacky way to do generative testing *right now* and isn't conducive to shrinking. I've been debating between approaches to change this very soon. (It's also rspec specific unfortunately, right now... the hacky part is taking advantage of the lazy evaluation of `let` in rspec).

I'm very interested in seeing generative and property based testing be more widely adopted in the Ruby community.

**Comment by nightscape** [comment]
Oh, wow, I haven't found generative because I was always searching for property testing. I didn't know generative testing as term existed.
generative looks very nice, it might just be what I was looking for (especiallly the RSpec integration)!
